version: "3.7"

services:
    db:
      image: postgres
      restart: always
      ports: 
        - "5432:5432"
      environment:
        - POSTGRES_USER=TheDoctor
        - POSTGRES_PASSWORD=secret
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - db:/var/lib/postgresql/data/pgdata
    redis:
      image: "redis:alpine"
      ports: 
        - 6379:6379

volumes:
    db: