"""empty message

Revision ID: 47b669623b3b
Revises: 0f3cf3d10769
Create Date: 2020-03-26 09:48:57.565539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b669623b3b'
down_revision = '0f3cf3d10769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment_terms', 'current_term',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment_terms', 'current_term',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
