"""empty message

Revision ID: 7c675bb74a08
Revises: 47b669623b3b
Create Date: 2020-04-01 16:42:32.239462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c675bb74a08'
down_revision = '47b669623b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_averages')
    op.create_foreign_key(None, 'courses', 'enrollment_terms', ['enrollment_term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_table('outcome_averages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outcome_avg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='outcome_averages_course_id_fkey'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], name='outcome_averages_outcome_id_fkey'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='outcome_averages_record_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='outcome_averages_pkey')
    )
    # ### end Alembic commands ###
