"""add section to CourseUsersLink model

Revision ID: 867b430f20d1
Revises: 6727f4a3ad1d
Create Date: 2021-11-15 20:40:06.057499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867b430f20d1'
down_revision = '6727f4a3ad1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_user_link', sa.Column('section_id', sa.Integer()))
    op.add_column('course_user_link', sa.Column('section_name', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_user_link', 'section_name')
    op.drop_column('course_user_link', 'section_id')
    # ### end Alembic commands ###
