"""add sync term column to enrollment terms

Revision ID: 8ee44e05fc58
Revises: 6b8cc66e5f0f
Create Date: 2020-12-24 15:27:38.036175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee44e05fc58'
down_revision = '6b8cc66e5f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_terms', sa.Column('sync_term', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_terms', 'sync_term')
    # ### end Alembic commands ###
