"""empty message

Revision ID: 9ed41acce64b
Revises: b0d9c444a201
Create Date: 2020-04-03 15:00:24.925572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed41acce64b'
down_revision = 'b0d9c444a201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_terms', sa.Column('cut_off_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_terms', 'cut_off_date')
    # ### end Alembic commands ###
