"""empty message

Revision ID: b0d9c444a201
Revises: 440c17b78fc8
Create Date: 2020-04-03 08:40:44.393233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0d9c444a201'
down_revision = '440c17b78fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_calculation',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
    sa.Column('grade_rank', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_rank')
    )
    op.drop_table('grade_criteria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_criteria',
    sa.Column('grade_rank', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('threshold', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('grade_rank', name='grade_criteria_pkey')
    )
    op.drop_table('grade_calculation')
    # ### end Alembic commands ###
