"""add sis_course_id column to courses

Revision ID: d56418d9ed52
Revises: 287413e4a49e
Create Date: 2021-07-28 21:23:49.216118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56418d9ed52'
down_revision = '287413e4a49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('sis_course_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'sis_course_id')
    # ### end Alembic commands ###
