"""empty message

Revision ID: d79570e56598
Revises: 47b669623b3b
Create Date: 2020-04-01 11:34:13.436649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79570e56598'
down_revision = '47b669623b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'courses', 'enrollment_terms', ['enrollment_term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    # ### end Alembic commands ###
